window.FALLBACK_SCHOOLS = [
  {
    id: "school_1",
    name: "エトワールバレエ",
    area: "東京",
    method: "ワガノワ",
    nearestStation: "表参道駅",
    ages: ["キッズ", "ジュニア", "プロ", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=600",
    description: "初めてバレエに触れるお子様から、趣味として楽しみたい大人の方まで、一人ひとりのペースに合わせて丁寧に指導します。アットホームな雰囲気の中で、踊る楽しさと豊かな表現力を身につけることができます。無理のないステップアップを目指すため、運動が苦手な方でも安心して始められます。無料体験レッスンも随時受け付けていますので、まずはスタジオの雰囲気を体感してみてください。",
    address: "東京都渋谷区神宮前1-2-3",
    affiliateUrl: "https://example.com/etoile",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+A",
    studyRows: [{ country: "ロシア", school: "ボリショイバレエ学校" }],
    contestRows: [{ year: "2025", count: "1件", name: "ローザンヌ国際バレエコンクール" }, { year: "2025", count: "4件", name: "(その他)国内コンクール" }]
  },
  {
    id: "school_2",
    name: "ローズバレエ",
    area: "神奈川",
    method: "RAD",
    nearestStation: "横浜駅",
    ages: ["キッズ", "ジュニア"],
    premium: false,
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600",
    description: "毎日の忙しさから離れ、美しくしなやかな身体を目指す大人のためのバレエスタジオです。姿勢改善や体幹の強化、柔軟性の向上など、それぞれの目的に合わせたクラスを用意しています。未経験からスタートした会員様が多く、基礎からじっくり学べる環境が整っています。駅からも近く、仕事帰りや休日のリフレッシュに最適な空間で、心地よい汗を流してみませんか。",
    address: "神奈川県横浜市中区元町4-5-6",
    affiliateUrl: "https://example.com/rose",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+B",
    studyRows: [{ country: "モナコ", school: "プリンセスグレースアカデミー" }],
    contestRows: [{ year: "2024", count: "2件", name: "(その他)国内コンクール" }]
  },
  {
    id: "school_3",
    name: "クララバレエ",
    area: "千葉",
    method: "チェケッティ",
    nearestStation: "船橋駅",
    ages: ["ジュニア", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=600",
    description: "プロを目指すジュニアから、さらなる技術向上を目指す経験者まで、質の高い指導を提供する本格派のバレエスクールです。国内外で活躍した実績を持つ講師陣が、一人ひとりの身体の特性を見極めながら、確かなテクニックと芸術性を引き出します。コンクールへの挑戦や留学のサポート体制も充実しており、高い目標に向かって互いに高め合える環境がここにあります。",
    address: "千葉県船橋市本町7-8-9",
    affiliateUrl: "https://example.com/clara",
    classImage: "",
    studyRows: [],
    contestRows: [{ year: "2025", count: "1件", name: "YAGP" }]
  },
  {
    id: "school_4",
    name: "ルミエールバレエ埼玉",
    area: "埼玉",
    method: "RAD",
    nearestStation: "大宮駅",
    ages: ["キッズ", "ジュニア", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=600",
    description: "美しい姿勢と豊かな表現力を育むバレエスタジオです。小さなお子様から趣味の大人の方まで、英国RADメソッドに基づき基礎から丁寧に指導します。アットホームな雰囲気の中で、楽しく踊りながら体幹を鍛え、しなやかな体を作ります。",
    address: "埼玉県さいたま市大宮区高鼻町1-2-3",
    affiliateUrl: "https://example.com/lumiere",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+E",
    studyRows: [{ country: "イギリス", school: "ロイヤルバレエ学校" }],
    contestRows: [{ year: "2025", count: "2件", name: "国内バレエコンクール" }, { year: "2024", count: "1件", name: "国際コンクール" }]
  },
  {
    id: "school_5",
    name: "ソレイユバレエ大阪",
    area: "大阪",
    method: "ワガノワ",
    nearestStation: "梅田駅",
    ages: ["キッズ", "ジュニア", "プロ"],
    premium: false,
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600",
    description: "プロを目指す本格的なジュニアから、基礎をしっかり学びたいお子様のためのスクールです。ワガノワメソッドに準拠した質の高いレッスンを提供し、国内外のコンクール入賞や留学を目指す生徒を全力でサポートします。",
    address: "大阪府大阪市北区梅田2-3-4",
    affiliateUrl: "https://example.com/soleil",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+F",
    studyRows: [{ country: "ロシア", school: "ワガノワバレエアカデミー" }],
    contestRows: [{ year: "2025", count: "3件", name: "YAGP" }, { year: "2024", count: "2件", name: "ローザンヌ国際バレエコンクール" }]
  },
  {
    id: "school_6",
    name: "ミモザバレエ京都",
    area: "京都",
    method: "チェケッティ",
    nearestStation: "京都駅",
    ages: ["ジュニア", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=600",
    description: "大人のための気品あるバレエスタジオです。初心者の方でも安心して始められるよう、チェケッティメソッドの基礎からゆっくり指導します。日常の忙しさから離れ、音楽に合わせて体を動かす心地よさを体験してください。",
    address: "京都府京都市中京区烏丸通1-2",
    affiliateUrl: "https://example.com/mimosa",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+G",
    studyRows: [],
    contestRows: [{ year: "2025", count: "1件", name: "国内コンクール" }]
  },
  {
    id: "school_7",
    name: "アイリスバレエ兵庫",
    area: "兵庫",
    method: "パリ・オペラ座",
    nearestStation: "三宮駅",
    ages: ["キッズ", "ジュニア", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=600",
    description: "フランスのエレガントなバレエスタイルを学ぶことができるスタジオです。表現力と正確なテクニックを身につけるため、経験豊富な講師陣が一人ひとりに合わせた指導を行います。無料体験レッスンも随時開催しています。",
    address: "兵庫県神戸市中央区三宮町3-4-5",
    affiliateUrl: "https://example.com/iris",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+H",
    studyRows: [{ country: "フランス", school: "パリ・オペラ座バレエ学校" }],
    contestRows: [{ year: "2024", count: "1件", name: "国際バレエコンクール" }, { year: "2023", count: "2件", name: "国内コンクール" }]
  },
  {
    id: "school_8",
    name: "エクラバレエ愛知",
    area: "愛知",
    method: "バランシン",
    nearestStation: "名古屋駅",
    ages: ["ジュニア", "プロ", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600",
    description: "ダイナミックでスピーディーなバランシンメソッドを取り入れた、実践的なレッスンが特徴のスクールです。テクニックの向上はもちろん、音楽性と芸術性を最大限に引き出す指導で、ダンサーとしての可能性を広げます。",
    address: "愛知県名古屋市中村区名駅4-5-6",
    affiliateUrl: "https://example.com/eclat",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+I",
    studyRows: [{ country: "アメリカ", school: "スクールオブアメリカンバレエ" }],
    contestRows: [{ year: "2025", count: "2件", name: "YAGP" }]
  },
  {
    id: "school_9",
    name: "シルフィードバレエ福岡",
    area: "福岡",
    method: "RAD",
    nearestStation: "天神駅",
    ages: ["キッズ", "ジュニア"],
    premium: false,
    image: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=600",
    description: "子どもたちの感性と健やかな身体を育てるバレエ教室です。リズム感を養いながら、正しい姿勢と柔軟性を自然に身につけていきます。お友達と一緒に楽しく踊りながら、協調性やマナーも学ぶことができます。",
    address: "福岡県福岡市中央区天神2-3-4",
    affiliateUrl: "https://example.com/sylphide",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+J",
    studyRows: [],
    contestRows: [{ year: "2025", count: "1件", name: "国内バレエコンクール" }]
  },
  {
    id: "school_10",
    name: "オーロラバレエ北海道",
    area: "北海道",
    method: "ワガノワ",
    nearestStation: "札幌駅",
    ages: ["キッズ", "ジュニア", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=600",
    description: "北の大地で本格的なバレエを学びませんか。初心者から経験者まで、それぞれのレベルに応じた細やかなクラス編成が魅力です。舞台に立つ喜びを通じて、豊かな人間性と自信を身につけることを目指します。",
    address: "北海道札幌市中央区北1条西2-3",
    affiliateUrl: "https://example.com/aurora",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+K",
    studyRows: [{ country: "カナダ", school: "カナダ国立バレエ学校" }],
    contestRows: [{ year: "2024", count: "1件", name: "国内コンクール" }]
  },
  {
    id: "school_11",
    name: "ステラバレエ宮城",
    area: "宮城",
    method: "なし",
    nearestStation: "青葉駅",
    ages: ["大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600",
    description: "仕事帰りや休日にリフレッシュしたい大人のための専用スタジオです。未経験から始めた方が多く、基本のステップから丁寧に教えるので安心です。健康維持、シェイプアップ、美しい立ち振る舞いなど、目的に合わせて通えます。",
    address: "宮城県仙台市青葉区中央1-2-3",
    affiliateUrl: "https://example.com/stella",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+L",
    studyRows: [],
    contestRows: []
  },
  {
    id: "school_12",
    name: "フローラバレエ広島",
    area: "広島",
    method: "チェケッティ",
    nearestStation: "広島駅",
    ages: ["キッズ", "ジュニア", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=600",
    description: "踊る楽しさを最優先に、基礎から応用まで体系的に学べるスクールです。一人ひとりの個性を大切にしながら、音楽に合わせた美しい表現力を引き出します。定期的な発表会で、日頃の練習の成果を披露する舞台もあります。",
    address: "広島県広島市中区紙屋町1-2-3",
    affiliateUrl: "https://example.com/flora",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+M",
    studyRows: [{ country: "ドイツ", school: "ジョンクランコバレエ学校" }],
    contestRows: [{ year: "2025", count: "1件", name: "国内コンクール" }, { year: "2024", count: "1件", name: "YAGP" }]
  },
  {
    id: "school_13",
    name: "ピルエットバレエ静岡",
    area: "静岡",
    method: "RAD",
    nearestStation: "静岡駅",
    ages: ["キッズ", "ジュニア", "プロ", "大人"],
    premium: false,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=600",
    description: "国内外で豊富な経験を持つ講師が指導する本格的なスタジオです。小さなお子様の情操教育から、プロを目指す専門コース、大人の美容クラスまで幅広く対応しています。基礎を大切に、怪我のない体作りを重視します。",
    address: "静岡県静岡市葵区追手町1-2-3",
    affiliateUrl: "https://example.com/pirouette",
    classImage: "https://placehold.co/800x600/fff1f5/be2f67?text=Schedule+N",
    studyRows: [{ country: "オーストラリア", school: "オーストラリアンバレエ学校" }],
    contestRows: [{ year: "2025", count: "2件", name: "ローザンヌ国際バレエコンクール" }, { year: "2024", count: "3件", name: "国内コンクール" }]
  }
];
